START TRANSACTION;

DROP TABLE IF EXISTS `address`;

DROP TABLE IF EXISTS `cart`;

DROP TABLE IF EXISTS `delivery`;

DROP TABLE IF EXISTS `feature`;

DROP TABLE IF EXISTS `order`;

DROP TABLE IF EXISTS `product`;

DROP TABLE IF EXISTS `role`;

DROP TABLE IF EXISTS `user`;

DROP TABLE IF EXISTS `wish_list`;

COMMIT;